using System;

namespace Autofac
{
    public class MessageA : IMessage
    {
        public void Display()
        {
            Console.WriteLine("This is the message that has been generated by the injected class.");
        }
    }
}
